### PR TITLE
deduce value for vcollective implementation from environment, fixes #28

### LINKED ISSUE #28: support runtime control of options
Right now, v-coll algorithms are hardcoded to be P2P.  This should be a runtime option via env var.

### PR DESCRIPTION
**Pull request by gentryx**

### CODE REVIEW

**Comment by jeffhammond** [comment]
Can you put these functions in the BigMPI namespace instead?

I will postpone my misgivings about the thread-unsafety of this implementation because I can fix it later :-)

A more general approach to configuring such options is to add `BigMPI_Init`, but I have been trying to avoid that because of the drop-in replacement ideal.

**Comment by gentryx** [comment]
1. ACK, will move to namespace.

2. I did think about thread safety, but a) that's hard to do portable and b) we're writing basically two ints, and each write is hence atomic (unless an int would represent multiple machine words, which it doesn't). Hence, even if two threads were calling the setup function, and even if the value of the environment variable would change in the mean time, the result would still be uncorrupted.

3. Yeah, I did think about adding an init function, but dropped that idea for the same reason.

**Comment by jeffhammond** [comment]
For thread-safety, I would support C11, GCC atomic intrinsics, and
Pthreads.  Do you think that's not enough?  If your objection comes from
Visual C++ i.e. Windows, then I will revoke your commit privileges ;-)

On Thu, Oct 29, 2015 at 10:59 AM, Andreas Schäfer <notifications@github.com>
wrote:

>
>    1.
>
>    ACK, will move to namespace.
>    2.
>
>    I did think about thread safety, but a) that's hard to do portable and
>    b) we're writing basically two ints, and each write is hence atomic (unless
>    an int would represent multiple machine words, which it doesn't). Hence,
>    even if two threads were calling the setup function, and even if the value
>    of the environment variable would change in the mean time, the result would
>    still be uncorrupted.
>    3.
>
>    Yeah, I did think about adding an init function, but dropped that idea
>    for the same reason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeffhammond/BigMPI/pull/29#issuecomment-152266966>.
>



-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by gentryx** [comment]
Might suffice. I still don't see the race condition though. Let's call it a lock-less data structure and hence a feature, yes yes? ;-)

**Comment by jeffhammond** [comment]
The race arises from load/store of `initialized` and `default_value` not being atomic.
```
if (!initialized) {
  default_value = ..;
  initialized = 1;
}
```
If two threads enter this code, it is possible that store tearing will result in bogus data being written to `default_value`.  This section should either be protected by a lock or `initialized` should be an atomic integer type and the region protected by fetch-and-increment.

**Comment by gentryx** [comment]
Is store tearing possible for ints (which enums basically are)? I was under the impression that it's not.

**Comment by jeffhammond** [comment]
Store tearing for aligned 32b integers is not possible on all the major architectures (See [Preshing](http://preshing.com/20130618/atomic-vs-non-atomic-operations/) for details).  However, it is not guaranteed by ISO C or POSIX from what I can tell.

While it may be ironic to some that an Intel employee does not want to assume store atomicity, I'm not willing to do so since there are completely portable alternatives that don't negatively impact performance.

**Comment by gentryx** [comment]
Well, you're the maintainer. :-) Would you still merge the PR?

**Comment by jeffhammond** [comment]
Yeah, because I know we have other thread-safety issues, such as P2P implementations of collectives not being correct in the case of MPI_THREAD_MULTIPLE, because if two threads enter BigMPI at the same time, the Send-Recv calls may cross-match.

**Pull request merged**
